import type { WatchlistItem } from "./types"

export function watchlistItem(overrides: Partial<WatchlistItem> = {}): WatchlistItem {
  return {
    id: 7,
    symbol: "NABIL",
    name: "Nabil Bank Limited",
    sector: "Commercial Banks",
    setup_type: "vcp",
    status: "watching",
    price_state: "below_zone",
    entry_zone_low: 570,
    entry_zone_high: 587.1,
    invalidation_price: 548,
    stop_loss_price: 548,
    target_price: 640,
    pivot_price: 570,
    price_at_add: 560,
    current_price: 565,
    change_percent: 0.71,
    price_updated_at: "2026-09-27T09:00:00Z",
    distance_to_zone_pct: 0.88,
    risk_reward: 3.18,
    setup_snapshot: { vcp_score: 72, contractions_count: 3, trend: "uptrend", market_regime: "bullish", analysed_on: "2026-09-24" },
    notes: "Tight T3 on drying volume",
    trade_plan_id: null,
    last_evaluated_at: "2026-09-27T09:00:00Z",
    created_at: "2026-09-27T08:00:00Z",
    last_close_on: null,
    last_close_state: null,
    last_close_price: null,
    last_close_relative_volume: null,
    checklist: {
      passed: 3,
      total: 7,
      all_passed: false,
      checks: [
        { key: "pattern", label: "Qualified VCP", status: "pass", detail: "Score 80, 13.4% -> 5.4%" },
        { key: "close", label: "Closed above the pivot", status: "pending", detail: "Judged after the 4 PM close" },
        { key: "volume", label: "Volume at least 1.5x average at the close", status: "pending", detail: "Judged after the 4 PM close" },
        { key: "regime", label: "Market regime not weak", status: "pass", detail: "Market neutral" },
        { key: "sector", label: "Sector stronger than NEPSE (20 sessions)", status: "fail", detail: "Commercial Banks -2.10% vs NEPSE -1.20%" },
        { key: "risk_reward", label: "Risk:reward at least 2R", status: "pass", detail: "3.18R" },
        { key: "not_extended", label: "Price not above the entry zone", status: "pending", detail: null },
      ],
    },
    ...overrides,
  }
}
